services:
  - type: web
    name: filmdb
    runtime: python
    buildCommand: pip install cryptography
    startCommand: python server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SHEETS_CREDS
        sync: false
      - key: SPREADSHEET_ID
        value: 1sRXiN_W8oshYIZTaDza3A-B1MPgrpTmedoQx8VS9Dsw
routes:
  - type: rewrite
    source: /*
    destination: /
